apiVersion: apps/v1
kind: Deployment
metadata:
  name: webrtc-app
  labels:
    app: webrtc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webrtc
  template:
    metadata:
      labels:
        app: webrtc
    spec:
      containers:
      - name: webrtc-app
        image: ghcr.io/samithaagrapala/webrtc-app:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
        - name: PORT
          value: "3000"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20 