apiVersion: v1
kind: Service
metadata:
  name: webrtc-video-conferencing
  labels:
    app: webrtc-video-conferencing
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  - port: 443
    targetPort: 3000
    protocol: TCP
    name: https
  selector:
    app: webrtc-video-conferencing 